# f26_accumulation_distribution_slope_001_150_gemini.py
import pandas as pd
import numpy as np

def _mf_mult(h: pd.Series, l: pd.Series, c: pd.Series) -> pd.Series:
    return ((c - l) - (h - c)) / (h - l).abs().replace(0, np.nan)

def _mf_vol(mult: pd.Series, v: pd.Series) -> pd.Series:
    return mult * v

def _ad_osc(mfv: pd.Series, w: int) -> pd.Series:
    return mfv.rolling(w).sum() / mfv.rolling(w).std().abs().replace(0, np.nan)

def _sma(s: pd.Series, w: int) -> pd.Series:
    return s.rolling(w, min_periods=min(w, 5)).mean()

def _ema(s: pd.Series, w: int) -> pd.Series:
    return s.ewm(span=w, min_periods=min(w, 5), adjust=False).mean()

def _zscore(s: pd.Series, w: int) -> pd.Series:
    return (s - _sma(s, w)) / s.rolling(w, min_periods=min(w, 5)).std().replace(0, np.nan)

# Slope of Accumulation Distribution Oscillator 5d (ROC 5d)
def f26ad_accumulation_distribution_osc_slope_5d_v001_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 5)
    res = osc.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 10d (ROC 5d)
def f26ad_accumulation_distribution_osc_slope_10d_v002_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 10)
    res = osc.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 21d (ROC 5d)
def f26ad_accumulation_distribution_osc_slope_21d_v003_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 21)
    res = osc.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 42d (ROC 21d)
def f26ad_accumulation_distribution_osc_slope_42d_v004_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 42)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 63d (ROC 21d)
def f26ad_accumulation_distribution_osc_slope_63d_v005_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 63)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 84d (ROC 21d)
def f26ad_accumulation_distribution_osc_slope_84d_v006_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 84)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 126d (ROC 21d)
def f26ad_accumulation_distribution_osc_slope_126d_v007_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 126)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 168d (ROC 63d)
def f26ad_accumulation_distribution_osc_slope_168d_v008_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 168)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 252d (ROC 63d)
def f26ad_accumulation_distribution_osc_slope_252d_v009_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 252)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 336d (ROC 63d)
def f26ad_accumulation_distribution_osc_slope_336d_v010_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 336)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 504d (ROC 63d)
def f26ad_accumulation_distribution_osc_slope_504d_v011_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 504)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 756d (ROC 63d)
def f26ad_accumulation_distribution_osc_slope_756d_v012_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 756)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator 5d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 10d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 21d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 5d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 10d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 21d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 5d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 10d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 21d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator 5d (ROC 5d)
# Slope of Accumulation Distribution Oscillator 10d (ROC 5d)
# Slope of Accumulation Distribution relative volume 5d (ROC 5d)
def f26ad_accumulation_distribution_rel_vol_slope_5d_v051_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(5).sum() / volume.rolling(5).sum().replace(0, np.nan)
    res = rel_vol.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 10d (ROC 5d)
def f26ad_accumulation_distribution_rel_vol_slope_10d_v052_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(10).sum() / volume.rolling(10).sum().replace(0, np.nan)
    res = rel_vol.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 21d (ROC 5d)
def f26ad_accumulation_distribution_rel_vol_slope_21d_v053_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(21).sum() / volume.rolling(21).sum().replace(0, np.nan)
    res = rel_vol.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 42d (ROC 21d)
def f26ad_accumulation_distribution_rel_vol_slope_42d_v054_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(42).sum() / volume.rolling(42).sum().replace(0, np.nan)
    res = rel_vol.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 63d (ROC 21d)
def f26ad_accumulation_distribution_rel_vol_slope_63d_v055_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(63).sum() / volume.rolling(63).sum().replace(0, np.nan)
    res = rel_vol.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 84d (ROC 21d)
def f26ad_accumulation_distribution_rel_vol_slope_84d_v056_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(84).sum() / volume.rolling(84).sum().replace(0, np.nan)
    res = rel_vol.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 126d (ROC 21d)
def f26ad_accumulation_distribution_rel_vol_slope_126d_v057_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(126).sum() / volume.rolling(126).sum().replace(0, np.nan)
    res = rel_vol.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 168d (ROC 63d)
def f26ad_accumulation_distribution_rel_vol_slope_168d_v058_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(168).sum() / volume.rolling(168).sum().replace(0, np.nan)
    res = rel_vol.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 252d (ROC 63d)
def f26ad_accumulation_distribution_rel_vol_slope_252d_v059_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(252).sum() / volume.rolling(252).sum().replace(0, np.nan)
    res = rel_vol.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 336d (ROC 63d)
def f26ad_accumulation_distribution_rel_vol_slope_336d_v060_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(336).sum() / volume.rolling(336).sum().replace(0, np.nan)
    res = rel_vol.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 504d (ROC 63d)
def f26ad_accumulation_distribution_rel_vol_slope_504d_v061_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(504).sum() / volume.rolling(504).sum().replace(0, np.nan)
    res = rel_vol.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 756d (ROC 63d)
def f26ad_accumulation_distribution_rel_vol_slope_756d_v062_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(756).sum() / volume.rolling(756).sum().replace(0, np.nan)
    res = rel_vol.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution relative volume 5d (ROC 5d)
# Slope of Accumulation Distribution relative volume 10d (ROC 5d)
# Slope of Accumulation Distribution relative volume 21d (ROC 5d)
# Slope of Accumulation Distribution relative volume 42d (ROC 21d)
# Slope of Accumulation Distribution relative volume 63d (ROC 21d)
# Slope of Accumulation Distribution relative volume 84d (ROC 21d)
# Slope of Accumulation Distribution relative volume 126d (ROC 21d)
# Slope of Accumulation Distribution relative volume 168d (ROC 63d)
# Slope of Accumulation Distribution relative volume 252d (ROC 63d)
# Slope of Accumulation Distribution relative volume 336d (ROC 63d)
# Slope of Accumulation Distribution relative volume 504d (ROC 63d)
# Slope of Accumulation Distribution relative volume 756d (ROC 63d)
# Slope of Accumulation Distribution relative volume 5d (ROC 5d)
# Slope of Accumulation Distribution relative volume 10d (ROC 5d)
# Slope of Accumulation Distribution relative volume 21d (ROC 5d)
# Slope of Accumulation Distribution relative volume 42d (ROC 21d)
# Slope of Accumulation Distribution relative volume 63d (ROC 21d)
# Slope of Accumulation Distribution relative volume 84d (ROC 21d)
# Slope of Accumulation Distribution relative volume 126d (ROC 21d)
# Slope of Accumulation Distribution relative volume 168d (ROC 63d)
# Slope of Accumulation Distribution relative volume 252d (ROC 63d)
# Slope of Accumulation Distribution relative volume 336d (ROC 63d)
# Slope of Accumulation Distribution relative volume 504d (ROC 63d)
# Slope of Accumulation Distribution relative volume 756d (ROC 63d)
# Slope of Accumulation Distribution relative volume 5d (ROC 5d)
# Slope of Accumulation Distribution relative volume 10d (ROC 5d)
# Slope of Accumulation Distribution relative volume 21d (ROC 5d)
# Slope of Accumulation Distribution relative volume 42d (ROC 21d)
# Slope of Accumulation Distribution relative volume 63d (ROC 21d)
# Slope of Accumulation Distribution relative volume 84d (ROC 21d)
# Slope of Accumulation Distribution relative volume 126d (ROC 21d)
# Slope of Accumulation Distribution relative volume 168d (ROC 63d)
# Slope of Accumulation Distribution relative volume 252d (ROC 63d)
# Slope of Accumulation Distribution relative volume 336d (ROC 63d)
# Slope of Accumulation Distribution relative volume 504d (ROC 63d)
# Slope of Accumulation Distribution relative volume 756d (ROC 63d)
# Slope of Accumulation Distribution relative volume 5d (ROC 5d)
# Slope of Accumulation Distribution relative volume 10d (ROC 5d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
def f26ad_accumulation_distribution_osc_adj_slope_42d_v101_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 42)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 63d (ROC 21d)
def f26ad_accumulation_distribution_osc_adj_slope_63d_v105_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 63)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 84d (ROC 21d)
def f26ad_accumulation_distribution_osc_adj_slope_84d_v106_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 84)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 126d (ROC 21d)
def f26ad_accumulation_distribution_osc_adj_slope_126d_v107_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 126)
    res = osc.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 168d (ROC 63d)
def f26ad_accumulation_distribution_osc_adj_slope_168d_v108_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 168)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 252d (ROC 63d)
def f26ad_accumulation_distribution_osc_adj_slope_252d_v109_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 252)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 336d (ROC 63d)
def f26ad_accumulation_distribution_osc_adj_slope_336d_v110_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 336)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 504d (ROC 63d)
def f26ad_accumulation_distribution_osc_adj_slope_504d_v111_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 504)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 756d (ROC 63d)
def f26ad_accumulation_distribution_osc_adj_slope_756d_v112_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 756)
    res = osc.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 63d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 84d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 126d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 168d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 252d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 336d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 504d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 756d (ROC 63d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
# Slope of Accumulation Distribution Oscillator adjusted 42d (ROC 21d)
SILVERDB_ACCESS, SOURCE_TABLE, ENTITY_COLUMN, DATE_COLUMN = "read_only", "sep", "ticker", "date"
ORDER_BY, NO_FORWARD_LOOKING = [ENTITY_COLUMN, DATE_COLUMN], True
SOURCE_COLUMNS = {c: f"sep.{c}" for c in ["close", "closeadj", "high", "low", "volume"]}

SLOPE_NAMES = [f for f in globals() if f.startswith("f26ad_") and f.endswith("_signal")]

F26_ACCUMULATION_DISTRIBUTION_SLOPE_REGISTRY_001_150 = {
    n: {
        "inputs": (inputs := [v for v in globals()[n].__code__.co_varnames[:globals()[n].__code__.co_argcount]]),
        "source_table": SOURCE_TABLE,
        "source_columns": {c: SOURCE_COLUMNS[c] for c in inputs if c in SOURCE_COLUMNS},
        "entity_column": ENTITY_COLUMN, "date_column": DATE_COLUMN,
        "order_by": ORDER_BY, "no_forward_looking": NO_FORWARD_LOOKING, "func": globals()[n]
    } for n in sorted(SLOPE_NAMES)
}

if __name__ == "__main__":
    sz = 500; d = pd.DataFrame({"close": np.random.randn(sz).cumsum()+100, "closeadj": np.random.randn(sz).cumsum()+100, "high": np.random.randn(sz).cumsum()+110, "low": np.random.randn(sz).cumsum()+90, "volume": np.random.randint(100, 1000, sz).astype(float), "ticker": ["T"]*sz, "date": pd.date_range("2020-01-01", periods=sz)})
    for n, c in F26_ACCUMULATION_DISTRIBUTION_SLOPE_REGISTRY_001_150.items():
        r = c["func"](**{i: d[i] for i in c["inputs"]})
        assert isinstance(r, pd.Series)
    print("slope 001-150 OK")
