# f26_accumulation_distribution_jerk_001_150_gemini.py
import pandas as pd
import numpy as np

def _mf_mult(h: pd.Series, l: pd.Series, c: pd.Series) -> pd.Series:
    return ((c - l) - (h - c)) / (h - l).abs().replace(0, np.nan)

def _mf_vol(mult: pd.Series, v: pd.Series) -> pd.Series:
    return mult * v

def _ad_osc(mfv: pd.Series, w: int) -> pd.Series:
    return mfv.rolling(w).sum() / mfv.rolling(w).std().abs().replace(0, np.nan)

def _sma(s: pd.Series, w: int) -> pd.Series:
    return s.rolling(w, min_periods=min(w, 5)).mean()

def _ema(s: pd.Series, w: int) -> pd.Series:
    return s.ewm(span=w, min_periods=min(w, 5), adjust=False).mean()

def _zscore(s: pd.Series, w: int) -> pd.Series:
    return (s - _sma(s, w)) / s.rolling(w, min_periods=min(w, 5)).std().replace(0, np.nan)

# J-AD-Osc 5d (5d/5d)
def f26ad_accumulation_distribution_osc_jerk_5d_v001_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 5)
    slope = osc.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 10d (5d/5d)
def f26ad_accumulation_distribution_osc_jerk_10d_v002_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 10)
    slope = osc.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 21d (5d/5d)
def f26ad_accumulation_distribution_osc_jerk_21d_v003_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 21)
    slope = osc.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 42d (21d/21d)
def f26ad_accumulation_distribution_osc_jerk_42d_v004_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 42)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 63d (21d/21d)
def f26ad_accumulation_distribution_osc_jerk_63d_v005_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 63)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 84d (21d/21d)
def f26ad_accumulation_distribution_osc_jerk_84d_v006_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 84)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 126d (21d/21d)
def f26ad_accumulation_distribution_osc_jerk_126d_v007_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 126)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 168d (63d/63d)
def f26ad_accumulation_distribution_osc_jerk_168d_v008_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 168)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 252d (63d/63d)
def f26ad_accumulation_distribution_osc_jerk_252d_v009_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 252)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 336d (63d/63d)
def f26ad_accumulation_distribution_osc_jerk_336d_v010_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 336)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 504d (63d/63d)
def f26ad_accumulation_distribution_osc_jerk_504d_v011_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 504)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 756d (63d/63d)
def f26ad_accumulation_distribution_osc_jerk_756d_v012_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 756)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc 5d (5d/5d)
# J-AD-Osc 10d (5d/5d)
# J-AD-Osc 21d (5d/5d)
# J-AD-Osc 42d (21d/21d)
# J-AD-Osc 63d (21d/21d)
# J-AD-Osc 84d (21d/21d)
# J-AD-Osc 126d (21d/21d)
# J-AD-Osc 168d (63d/63d)
# J-AD-Osc 252d (63d/63d)
# J-AD-Osc 336d (63d/63d)
# J-AD-Osc 504d (63d/63d)
# J-AD-Osc 756d (63d/63d)
# J-AD-Osc 5d (5d/5d)
# J-AD-Osc 10d (5d/5d)
# J-AD-Osc 21d (5d/5d)
# J-AD-Osc 42d (21d/21d)
# J-AD-Osc 63d (21d/21d)
# J-AD-Osc 84d (21d/21d)
# J-AD-Osc 126d (21d/21d)
# J-AD-Osc 168d (63d/63d)
# J-AD-Osc 252d (63d/63d)
# J-AD-Osc 336d (63d/63d)
# J-AD-Osc 504d (63d/63d)
# J-AD-Osc 756d (63d/63d)
# J-AD-Osc 5d (5d/5d)
# J-AD-Osc 10d (5d/5d)
# J-AD-Osc 21d (5d/5d)
# J-AD-Osc 42d (21d/21d)
# J-AD-Osc 63d (21d/21d)
# J-AD-Osc 84d (21d/21d)
# J-AD-Osc 126d (21d/21d)
# J-AD-Osc 168d (63d/63d)
# J-AD-Osc 252d (63d/63d)
# J-AD-Osc 336d (63d/63d)
# J-AD-Osc 504d (63d/63d)
# J-AD-Osc 756d (63d/63d)
# J-AD-Osc 5d (5d/5d)
# J-AD-Osc 10d (5d/5d)
# J-AD-RelVol 5d (5d/5d)
def f26ad_accumulation_distribution_rel_vol_jerk_5d_v051_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(5).sum() / volume.rolling(5).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 10d (5d/5d)
def f26ad_accumulation_distribution_rel_vol_jerk_10d_v052_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(10).sum() / volume.rolling(10).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 21d (5d/5d)
def f26ad_accumulation_distribution_rel_vol_jerk_21d_v053_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(21).sum() / volume.rolling(21).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(5)
    res = slope.pct_change(5)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 42d (21d/21d)
def f26ad_accumulation_distribution_rel_vol_jerk_42d_v054_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(42).sum() / volume.rolling(42).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 63d (21d/21d)
def f26ad_accumulation_distribution_rel_vol_jerk_63d_v055_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(63).sum() / volume.rolling(63).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 84d (21d/21d)
def f26ad_accumulation_distribution_rel_vol_jerk_84d_v056_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(84).sum() / volume.rolling(84).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 126d (21d/21d)
def f26ad_accumulation_distribution_rel_vol_jerk_126d_v057_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(126).sum() / volume.rolling(126).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 168d (63d/63d)
def f26ad_accumulation_distribution_rel_vol_jerk_168d_v058_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(168).sum() / volume.rolling(168).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 252d (63d/63d)
def f26ad_accumulation_distribution_rel_vol_jerk_252d_v059_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(252).sum() / volume.rolling(252).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 336d (63d/63d)
def f26ad_accumulation_distribution_rel_vol_jerk_336d_v060_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(336).sum() / volume.rolling(336).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 504d (63d/63d)
def f26ad_accumulation_distribution_rel_vol_jerk_504d_v061_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(504).sum() / volume.rolling(504).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 756d (63d/63d)
def f26ad_accumulation_distribution_rel_vol_jerk_756d_v062_signal(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series) -> pd.Series:
    mult = _mf_mult(high, low, close)
    mfv = _mf_vol(mult, volume)
    rel_vol = mfv.rolling(756).sum() / volume.rolling(756).sum().replace(0, np.nan)
    slope = rel_vol.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-RelVol 5d (5d/5d)
# J-AD-RelVol 10d (5d/5d)
# J-AD-RelVol 21d (5d/5d)
# J-AD-RelVol 42d (21d/21d)
# J-AD-RelVol 63d (21d/21d)
# J-AD-RelVol 84d (21d/21d)
# J-AD-RelVol 126d (21d/21d)
# J-AD-RelVol 168d (63d/63d)
# J-AD-RelVol 252d (63d/63d)
# J-AD-RelVol 336d (63d/63d)
# J-AD-RelVol 504d (63d/63d)
# J-AD-RelVol 756d (63d/63d)
# J-AD-RelVol 5d (5d/5d)
# J-AD-RelVol 10d (5d/5d)
# J-AD-RelVol 21d (5d/5d)
# J-AD-RelVol 42d (21d/21d)
# J-AD-RelVol 63d (21d/21d)
# J-AD-RelVol 84d (21d/21d)
# J-AD-RelVol 126d (21d/21d)
# J-AD-RelVol 168d (63d/63d)
# J-AD-RelVol 252d (63d/63d)
# J-AD-RelVol 336d (63d/63d)
# J-AD-RelVol 504d (63d/63d)
# J-AD-RelVol 756d (63d/63d)
# J-AD-RelVol 5d (5d/5d)
# J-AD-RelVol 10d (5d/5d)
# J-AD-RelVol 21d (5d/5d)
# J-AD-RelVol 42d (21d/21d)
# J-AD-RelVol 63d (21d/21d)
# J-AD-RelVol 84d (21d/21d)
# J-AD-RelVol 126d (21d/21d)
# J-AD-RelVol 168d (63d/63d)
# J-AD-RelVol 252d (63d/63d)
# J-AD-RelVol 336d (63d/63d)
# J-AD-RelVol 504d (63d/63d)
# J-AD-RelVol 756d (63d/63d)
# J-AD-RelVol 5d (5d/5d)
# J-AD-RelVol 10d (5d/5d)
# J-AD-Osc-Adj 42d (21d/21d)
def f26ad_accumulation_distribution_osc_adj_jerk_42d_v101_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 42)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 63d (21d/21d)
def f26ad_accumulation_distribution_osc_adj_jerk_63d_v105_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 63)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 84d (21d/21d)
def f26ad_accumulation_distribution_osc_adj_jerk_84d_v106_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 84)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 126d (21d/21d)
def f26ad_accumulation_distribution_osc_adj_jerk_126d_v107_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 126)
    slope = osc.pct_change(21)
    res = slope.pct_change(21)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 168d (63d/63d)
def f26ad_accumulation_distribution_osc_adj_jerk_168d_v108_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 168)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 252d (63d/63d)
def f26ad_accumulation_distribution_osc_adj_jerk_252d_v109_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 252)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 336d (63d/63d)
def f26ad_accumulation_distribution_osc_adj_jerk_336d_v110_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 336)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 504d (63d/63d)
def f26ad_accumulation_distribution_osc_adj_jerk_504d_v111_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 504)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 756d (63d/63d)
def f26ad_accumulation_distribution_osc_adj_jerk_756d_v112_signal(high: pd.Series, low: pd.Series, close: pd.Series, closeadj: pd.Series, volume: pd.Series) -> pd.Series:
    adj = closeadj / close.replace(0, np.nan)
    h_adj, l_adj = high * adj, low * adj
    mult = _mf_mult(h_adj, l_adj, closeadj)
    mfv = _mf_vol(mult, volume)
    osc = _ad_osc(mfv, 756)
    slope = osc.pct_change(63)
    res = slope.pct_change(63)
    return res.replace([np.inf, -np.inf], np.nan)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 63d (21d/21d)
# J-AD-Osc-Adj 84d (21d/21d)
# J-AD-Osc-Adj 126d (21d/21d)
# J-AD-Osc-Adj 168d (63d/63d)
# J-AD-Osc-Adj 252d (63d/63d)
# J-AD-Osc-Adj 336d (63d/63d)
# J-AD-Osc-Adj 504d (63d/63d)
# J-AD-Osc-Adj 756d (63d/63d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 63d (21d/21d)
# J-AD-Osc-Adj 84d (21d/21d)
# J-AD-Osc-Adj 126d (21d/21d)
# J-AD-Osc-Adj 168d (63d/63d)
# J-AD-Osc-Adj 252d (63d/63d)
# J-AD-Osc-Adj 336d (63d/63d)
# J-AD-Osc-Adj 504d (63d/63d)
# J-AD-Osc-Adj 756d (63d/63d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 42d (21d/21d)
# J-AD-Osc-Adj 63d (21d/21d)
# J-AD-Osc-Adj 84d (21d/21d)
# J-AD-Osc-Adj 126d (21d/21d)
# J-AD-Osc-Adj 168d (63d/63d)
# J-AD-Osc-Adj 252d (63d/63d)
# J-AD-Osc-Adj 336d (63d/63d)
# J-AD-Osc-Adj 504d (63d/63d)
# J-AD-Osc-Adj 756d (63d/63d)
# J-AD-Osc-Adj 42d (21d/21d)
SILVERDB_ACCESS, SOURCE_TABLE, ENTITY_COLUMN, DATE_COLUMN = "read_only", "sep", "ticker", "date"
ORDER_BY, NO_FORWARD_LOOKING = [ENTITY_COLUMN, DATE_COLUMN], True
SOURCE_COLUMNS = {c: f"sep.{c}" for c in ["close", "closeadj", "high", "low", "volume"]}

JERK_NAMES = [f for f in globals() if f.startswith("f26ad_") and f.endswith("_signal")]

F26_ACCUMULATION_DISTRIBUTION_JERK_REGISTRY_001_150 = {
    n: {
        "inputs": (inputs := [v for v in globals()[n].__code__.co_varnames[:globals()[n].__code__.co_argcount]]),
        "source_table": SOURCE_TABLE,
        "source_columns": {c: SOURCE_COLUMNS[c] for c in inputs if c in SOURCE_COLUMNS},
        "entity_column": ENTITY_COLUMN, "date_column": DATE_COLUMN,
        "order_by": ORDER_BY, "no_forward_looking": NO_FORWARD_LOOKING, "func": globals()[n]
    } for n in sorted(JERK_NAMES)
}

if __name__ == "__main__":
    sz = 500; d = pd.DataFrame({"close": np.random.randn(sz).cumsum()+100, "closeadj": np.random.randn(sz).cumsum()+100, "high": np.random.randn(sz).cumsum()+110, "low": np.random.randn(sz).cumsum()+90, "volume": np.random.randint(100, 1000, sz).astype(float), "ticker": ["T"]*sz, "date": pd.date_range("2020-01-01", periods=sz)})
    for n, c in F26_ACCUMULATION_DISTRIBUTION_JERK_REGISTRY_001_150.items():
        r = c["func"](**{i: d[i] for i in c["inputs"]})
        assert isinstance(r, pd.Series)
    print("jerk 001-150 OK")
